api_platform:
    title: 'Project Manager API'
    version: 1.0.0
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
